# Generated by Django 3.2.16 on 2022-10-18 00:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221016_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.recipe_image_file_path),
        ),
    ]
